# This patch is an example of setting arguments for the cAdvisor container.
# This set of arguments mirrors what the kubelet currently uses for cAdvisor, 
# enables only cpu, memory, and diskIO metrics, and shows only container metrics.
apiVersion: apps/v1 # for Kubernetes versions before 1.9.0 use apps/v1beta2
kind: DaemonSet
metadata:
  name: cadvisor
spec:
  template:
    spec:
      containers:
      - name: cadvisor
        args:
          - --storage_driver="statsd"
          - --storage_driver_host="localhost:8125"
